### ISSUE TITLE
HTML emails

### ISSUE THREAD

**Issue by timozattol** [zifeo/Myjob#19]
Design nice HTML emails to 

* notify students of new ads.
* confirm successful creation of an ad + secret edition url

**Comment by timozattol** [comment]
Also a mail to 
* confirm moderation of ad by the moderation team

**Comment by zifeo** [comment]
Adressed by #72.

**Comment by timozattol** [comment]
We still need 
* confirm moderation of ad by the moderation team
* confirm successful creation of an ad + secret edition url

right?

**Comment by zifeo** [comment]
Yup, best would be another issue…
